INSERT INTO dbo.Cursos (ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (1, 'SQL Server', '10/10/2025', 'SQL1')

INSERT INTO dbo.Cursos (ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (2, 'Oracle', '10/10/2025', 'ORACLE1');

INSERT INTO dbo.Cursos (ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (3, 'MySQL', '10/10/2025', 'MYSQL1');

INSERT INTO dbo.Cursos (ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (4, 'Java', '10/10/2025', 'JAVA1');

INSERT INTO dbo.Cursos (ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (5, 'Python', '10/10/2025', 'PYTHON1');

INSERT INTO dbo.Cursos (ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (6, 'C++', '10/10/2025', 'C++1');

INSERT INTO dbo.Cursos (ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (7, 'C#', '10/10/2025', 'C#1');

INSERT INTO dbo.Cursos (ID_CURSO, NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (8, 'Kotlin', '10/10/2025', 'Kotlin1');