INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (1, 'Presença Confirmada', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (2, 'Falta Justificada', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (3, 'Falta Injustificada', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (4, 'Atestado Médico', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (5, 'Licença Médica', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (6, 'Férias', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (7, 'Atestado de Ocorrência', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (8, 'Exame Médico', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (9, 'Provação de Conhecimento', '10/10/2025', 'Teste1');

INSERT INTO dbo.Situacao (ID_SITUACAO, SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO)
VALUES (10, 'Ausência', '10/10/2025', 'Teste1');